/*
 * This source file was generated by the Gradle 'init' task
 */
package ifsc.poo;

import java.util.Random;

public class App {
    public static void main(String[] args) {
        System.out.println("Classe Lâmpada:");
        Lampada lampada1 = new Lampada();     //Criação das lampadas
        Lampada lampada2 = new Lampada();

        lampada1.ligar(); //Setando estados das lâmpadas
        lampada2.desligar();

        System.out.println("Estado da lampada 1: " + lampada1.verEstado()); //Exibindo estados das lâmpadas
        System.out.println("Estado da lampada 2: " + lampada2.verEstado());

        System.out.println("-----+-----+-----+-----+");

        System.out.println("Classe Pessoa:");
        Pessoa pessoa1 = new Pessoa(); //Criação das pessoas
        Pessoa pessoa2 = new Pessoa();

        pessoa1.setNome("Alice"); //Criando pessoa Alice de 22 anos
        pessoa1.setIdade(22);

        pessoa2.setNome("Bruno"); //Criando pessoa Bruno de 25 anos
        pessoa2.setIdade(25);

        for(int i = 0; i < 3; i++){ //Comemorando o aniversário bruno 3 vezes
            pessoa2.felizAniversario();
        }

        System.out.println("Idade Alice: " + pessoa1.getIdade()); //Exibindo idades da Alice e do Bruno
        System.out.println("Idade Bruno: " + pessoa2.getIdade());

        pessoa1.setIdade(-44); //Exemplos de entradas inválidas
        pessoa2.setNome("");

        System.out.println("-----+-----+-----+-----+");

        System.out.println("Classe Retangulo:");
        Retangulo retangulo = new Retangulo();

        retangulo.setLargura(5); //Construção do retângulo
        retangulo.setAltura(4);

        System.out.println("Área: " + retangulo.getArea());  //Exibindo quais dimensões foram determinadas
        System.out.println("Perímetro: " + retangulo.getPerimetro());

        Retangulo[] retangulos = new Retangulo[10]; //Criação de um vetor do tipo objeto Retangulo
        Random r = new Random();
        float maior_razao = 0;

        for(int i = 0; i < 10; i++){ //Função em que gera retângulos de forma aleatória, e verifica a maior razao entre area / perimetro
            System.out.println("Retangulo " + (i + 1) + " :");
            float altura = r.nextFloat(9) + 1; //Altura e largura entre 1 - 10
            float largura = r.nextFloat(9) + 1;
            retangulo.setAltura(altura);
            retangulo.setLargura(largura);
            retangulos[i] = retangulo;
            float perimetro = retangulos[i].getPerimetro();
            float area = retangulos[i].getArea();
            float razao = area / perimetro;
            if(razao > maior_razao){
                maior_razao = razao;
            }
            System.out.println("Perímetro do Retangulo: " + perimetro);
            System.out.println("Área do Retangulo: " + area);
        }

        System.out.println("Maior razão entre área e perímetro do retangulo: " + maior_razao);

        System.out.println("-----+-----+-----+-----+");

        System.out.println("Classe relógio:");
        Relogio relogio = new Relogio();

        relogio.ajustaHora((byte) 14, (byte) 58, (byte) 32); //Hora inicial
        System.out.println(relogio.getHora()); //Exibe a hora no formato de 24 horas
        System.out.println(relogio.getHoraAMPM()); //Exibe a hora no formato de 12 horas

        for(int i = 0; i < 2; i++){
            relogio.avancaMinuto(); //Avança 2 minutos
        }

        System.out.println(relogio.getHora());
        System.out.println(relogio.getHoraAMPM());


        relogio.ajustaHora((byte) 23, (byte) 59, (byte) 59); //Determina uma nova hora
        relogio.avancaSegundo(); //Incrementa um segundo
        System.out.println(relogio.getHora());
        System.out.println(relogio.getHoraAMPM());

        System.out.println("-----+-----+-----+-----+");

        System.out.println("Classe produto:");
        Produto produto1 = new Produto();
        produto1.setNome("Geladeira"); //Nome do produto
        produto1.setPreco(832); //Preço do produto
        System.out.println("Nome: " + produto1.getNome() + ", Preço: " + produto1.getPreco());

        Produto produto2 = new Produto();
        produto2.setNome("Microondas");
        produto2.setPreco(499);
        System.out.println("Nome: " + produto2.getNome() + ", Preço: " + produto2.getPreco());

        produto1.setDesconto(6); //Desconto em % do produto
        produto2.setDesconto(12);

        System.out.println("Nome: " + produto1.getNome() + ", Preço: " + produto1.getPreco()); //Exibe nome do produto e seu preço na promoção
        System.out.println("Nome: " + produto2.getNome() + ", Preço: " + produto2.getPreco());

        System.out.println(produto1.anuncio());
        System.out.println(produto2.anuncio());

        System.out.println("-----+-----+-----+-----+");

        System.out.println("Classe Livro:");

        Livro livro = new Livro();

        livro.setTitulo("O Senhor dos Anéis - A Sociedade do Anel"); //Título do livro
        livro.setAutor("J. R. R. Tolkien"); //Autor do livro
        livro.setGeneros("Fantasia", "Aventura"); //Gêneros do Livro
        livro.setPaginas(464); //Quantidade de páginas

        String[] todos_caps = { //Títulos de todos os capítulos presentes no livro
        "Uma Festa Muito Esperada",
        "A Sombra do Passado",
        "Três é Demais",
        "Um Atalho para Cogumelos",
        "Uma Conspiração Desmascarada",
        "A Floresta Velha",
        "Em Casa de Tom Bombadil",
        "Névoa nas Colinas dos Túmulos",
        "No Pônei Empinado",
        "Passolargo",
        "Um Faca na Noite",
        "Voo para o Vau",
        "Muitos Encontros",
        "O Conselho de Elrond",
        "O Anel Vai para o Sul",
        "Uma Jornada no Escuro",
        "A Ponte de Khazad-dûm",
        "Lothlórien",
        "O Espelho de Galadriel",
        "Adeus a Lórien",
        "O Grande Rio",
        "A Partida da Sociedade"
        };

        //Página de início ed cada capítulo
        int[] inicio_cap = {1, 23, 44, 66, 89, 110, 131, 154, 176, 197, 219, 240, 261, 282, 301, 320, 341, 361, 383, 403, 423, 446};

        //Loop para setar os títulos de capítulos e suas páginas de início
        for (int i = 0; i < inicio_cap.length; i++) {
            livro.setTitulos_cap(todos_caps[i], inicio_cap[i]);
        }

        //Este bloco exibe as informações que foram setadas anteriormente
        System.out.println("Título: " + livro.getTitulo());
        System.out.println("Autor: " + livro.getAutor());
        System.out.println("Gêneros: " + livro.getGeneros()[0] + ", " + livro.getGeneros()[1]);
        System.out.println("Quantidade de Páginas: " + livro.getPaginas());
        String[] capitulos_reg = livro.getTitulos_cap();
        int[] paginas_reg = livro.getPagina_cap();
        System.out.print("Titulos: ");
        for (int i = 0; i < livro.getQtd_cap(); i++) {
            System.out.println(capitulos_reg[i]);
            System.out.println(paginas_reg[i]);
        }

        //Comportamento do livro durante a leitura
        livro.lerPaginas(90);
        System.out.println(livro.lendoAtual());
        livro.lerPaginas(300);
        System.out.println(livro.lendoAtual());
        livro.lerPaginas(100);
        System.out.println(livro.getPaginas_lidas());
    }
}

